<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        $students = [
            [
                'student_id' => 'STU2024001',
                'firebase_uid' => 'firebase_stu001',
                'firstname' => 'Alice',
                'lastname' => 'Anderson',
                'email' => 'alice.anderson@student.edu',
                'contact_number' => '555-1001',
                'course_id' => 1,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024002',
                'firebase_uid' => 'firebase_stu002',
                'firstname' => 'Bob',
                'lastname' => 'Baker',
                'email' => 'bob.baker@student.edu',
                'contact_number' => '555-1002',
                'course_id' => 1,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024003',
                'firebase_uid' => 'firebase_stu003',
                'firstname' => 'Carol',
                'lastname' => 'Chen',
                'email' => 'carol.chen@student.edu',
                'contact_number' => '555-1003',
                'course_id' => 1,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024004',
                'firebase_uid' => 'firebase_stu004',
                'firstname' => 'Daniel',
                'lastname' => 'Davis',
                'email' => 'daniel.davis@student.edu',
                'contact_number' => '555-1004',
                'course_id' => 1,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024005',
                'firebase_uid' => 'firebase_stu005',
                'firstname' => 'Emma',
                'lastname' => 'Evans',
                'email' => 'emma.evans@student.edu',
                'contact_number' => '555-1005',
                'course_id' => 1,
                'year' => 3,
            ],
            [
                'student_id' => 'STU2024006',
                'firebase_uid' => 'firebase_stu006',
                'firstname' => 'Frank',
                'lastname' => 'Fisher',
                'email' => 'frank.fisher@student.edu',
                'contact_number' => '555-1006',
                'course_id' => 1,
                'year' => 3,
            ],
            [
                'student_id' => 'STU2024007',
                'firebase_uid' => 'firebase_stu007',
                'firstname' => 'Grace',
                'lastname' => 'Garcia',
                'email' => 'grace.garcia@student.edu',
                'contact_number' => '555-1007',
                'course_id' => 1,
                'year' => 4,
            ],
            [
                'student_id' => 'STU2024008',
                'firebase_uid' => 'firebase_stu008',
                'firstname' => 'Henry',
                'lastname' => 'Harris',
                'email' => 'henry.harris@student.edu',
                'contact_number' => '555-1008',
                'course_id' => 1,
                'year' => 4,
            ],
            [
                'student_id' => 'STU2024009',
                'firebase_uid' => 'firebase_stu009',
                'firstname' => 'Ivy',
                'lastname' => 'Jackson',
                'email' => 'ivy.jackson@student.edu',
                'contact_number' => '555-1009',
                'course_id' => 1,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024010',
                'firebase_uid' => 'firebase_stu010',
                'firstname' => 'Jack',
                'lastname' => 'Jones',
                'email' => 'jack.jones@student.edu',
                'contact_number' => '555-1010',
                'course_id' => 1,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024011',
                'firebase_uid' => 'firebase_stu011',
                'firstname' => 'Katie',
                'lastname' => 'Kim',
                'email' => 'katie.kim@student.edu',
                'contact_number' => '555-1011',
                'course_id' => 2,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024012',
                'firebase_uid' => 'firebase_stu012',
                'firstname' => 'Liam',
                'lastname' => 'Lopez',
                'email' => 'liam.lopez@student.edu',
                'contact_number' => '555-1012',
                'course_id' => 2,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024013',
                'firebase_uid' => 'firebase_stu013',
                'firstname' => 'Maya',
                'lastname' => 'Martinez',
                'email' => 'maya.martinez@student.edu',
                'contact_number' => '555-1013',
                'course_id' => 2,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024014',
                'firebase_uid' => 'firebase_stu014',
                'firstname' => 'Noah',
                'lastname' => 'Nelson',
                'email' => 'noah.nelson@student.edu',
                'contact_number' => '555-1014',
                'course_id' => 2,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024015',
                'firebase_uid' => 'firebase_stu015',
                'firstname' => 'Olivia',
                'lastname' => 'Oliver',
                'email' => 'olivia.oliver@student.edu',
                'contact_number' => '555-1015',
                'course_id' => 2,
                'year' => 3,
            ],
            [
                'student_id' => 'STU2024016',
                'firebase_uid' => 'firebase_stu016',
                'firstname' => 'Peter',
                'lastname' => 'Parker',
                'email' => 'peter.parker@student.edu',
                'contact_number' => '555-1016',
                'course_id' => 2,
                'year' => 3,
            ],
            [
                'student_id' => 'STU2024017',
                'firebase_uid' => 'firebase_stu017',
                'firstname' => 'Quinn',
                'lastname' => 'Roberts',
                'email' => 'quinn.roberts@student.edu',
                'contact_number' => '555-1017',
                'course_id' => 1,
                'year' => 4,
            ],
            [
                'student_id' => 'STU2024018',
                'firebase_uid' => 'firebase_stu018',
                'firstname' => 'Rachel',
                'lastname' => 'Rodriguez',
                'email' => 'rachel.rodriguez@student.edu',
                'contact_number' => '555-1018',
                'course_id' => 1,
                'year' => 1,
            ],
            [
                'student_id' => 'STU2024019',
                'firebase_uid' => 'firebase_stu019',
                'firstname' => 'Samuel',
                'lastname' => 'Smith',
                'email' => 'samuel.smith@student.edu',
                'contact_number' => '555-1019',
                'course_id' => 2,
                'year' => 2,
            ],
            [
                'student_id' => 'STU2024020',
                'firebase_uid' => 'firebase_stu020',
                'firstname' => 'Tina',
                'lastname' => 'Turner',
                'email' => 'tina.turner@student.edu',
                'contact_number' => '555-1020',
                'course_id' => 2,
                'year' => 3,
            ],
        ];

        foreach ($students as $student) {
            DB::table('students')->updateOrInsert(
                ['student_id' => $student['student_id']],
                $student
            );
        }

        $this->command->info('✓ Created ' . count($students) . ' students');
    }
}
